name: Test Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    env:
      SBT_OPTS: "-Xms512M -Xmx2048M -Xss256m -XX:MaxMetaspaceSize=1024M"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1
      - name: Run tests and check formatting
        run: sbt scripted
